plugins {
    id "com.android.application"
}

android {
    namespace "com.heytap.wallet"
    compileSdk 36

    defaultConfig {
        applicationId "com.heytap.wallet"
        minSdk 31
        targetSdk 36
        versionCode 1008
        versionName "1.0.8"
        manifestPlaceholders = [walletOpenAction: "heytap.wallet.intent.action.OPEN"]
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    lint {
        abortOnError true
        checkReleaseBuilds true
    }
}
